# Site settings
# Access it in the templates via {{ site.myvariable }}.
title: Build an app with Azure SQL or SQL Server
description: > 
  Get started with Azure SQL DB on the cloud or SQL Server on macOS, Linux, and Windows.
url: https://sqlchoice.azurewebsites.net
destination: ../wwwroot/en-us/sql-server/developer-get-started
baseurl: /en-us/sql-server/developer-get-started

disqus:
  shortname: sqlchoice

gitter: https://gitter.im/Microsoft/mssql-developers

steps:
  1: Set up your environment
  2: Create $$ application with
  3: Make your $$ app up to 100x faster

menu:
  C#:
    logo: csharp.png
    pages:
      macOS: csharp/macos/server
      RHEL: csharp/rhel/server
      SLES: csharp/sles/server
      Ubuntu: csharp/ubuntu/server
      Windows: csharp/win/server
  Java:
    logo: java.png
    pages:
      macOS: java/macos/server
      RHEL: java/rhel/server
      SLES: java/sles/server
      Ubuntu: java/ubuntu/server
      Windows: java/windows/server
  Node.js:
    logo: node.png
    pages:
      macOS: node/macos/server
      RHEL: node/rhel/server
      SLES: node/sles/server
      Ubuntu: node/ubuntu/server
      Windows: node/windows/server
  PHP:
    logo: php.png
    pages:
      macOS: php/macos/server
      RHEL: php/rhel/server
      SLES: php/sles/server
      Ubuntu: php/ubuntu/server
      Windows: php/windows/server
  Python:
    logo: python.png
    pages:
      macOS: python/macos/server
      RHEL: python/rhel/server
      SLES: python/sles/server
      Ubuntu: python/ubuntu/server
      Windows: python/windows/server
  Ruby:
    logo: ruby.png
    pages:
      macOS: ruby/macos/server
      RHEL: ruby/rhel/server
      Ubuntu: ruby/ubuntu/server
  Go:
    logo: golang.png
    pages:
      macOS: go/macos/server
      RHEL: go/rhel/server
      SLES: go/sles/server
      Ubuntu: go/ubuntu/server
      Windows: go/windows/server
      
resources:
  sqlserver-csharp:
    pre: Check out what's new with
    text: SQL Server + C# on Channel 9
    link: https://channel9.msdn.com/Events/Connect/2016/151
    condition: C#
  sqlserver-java:
    pre: Check out what's new with
    text: SQL Server + Java on Channel 9
    link: https://channel9.msdn.com/Events/Connect/2016/152
    condition: Java
  sqlserver-node:
    pre: Check out what's new with
    text: SQL Server + Node.js on Channel 9
    link: https://channel9.msdn.com/Events/Connect/2016/160
    condition: Node.js
  sqlserver-php:
    pre: Check out what's new with
    text: SQL Server + PHP on Channel 9
    link: https://channel9.msdn.com/Events/Connect/2016/182
    condition: PHP
  sqlserver-py:
    pre: Check out what's new with
    text: SQL Server + Python on Channel 9
    link: https://channel9.msdn.com/Events/Connect/2016/189
    condition: Python
  github:
    pre: Browse more SQL Server code samples (In-Memory, Dynamic Data Masking, R, etc.) on our
    text: GitHub repository
    link: https://github.com/Microsoft/sql-server-samples/tree/master/samples/
  linux:
    pre: Learn more about
    text: SQL Server on Linux
    link: https://channel9.msdn.com/Events/Connect/2016/101
  connect:
    pre: Watch more
    text: Connect(); event videos
    link: https://channel9.msdn.com/Events/Connect/2016
  labs:
    pre: Browse our
    text: Virtual Labs Gallery
    link: https://technet.microsoft.com/en-us/virtuallabs

# Build settings
markdown: kramdown
theme: minima # we are extending it
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-redirect-from
